(load "insertFirst.ss")
(load "removeFirst.ss")
(load "listCopy.ss")
(load "oddCopy.ss")
(load "evenCopy.ss")
(load "insertLast.ss")
(load "removeLast.ss")
(load "append.ss")
(load "listReverse.ss")
(load "allReverse.ss")

(load "last.ss")
(load "lowerhalf.ss")
(load "upperhalf.ss")
(load "quicksort.ss")
(load "letterFilter.ss")
(load "qsort.ss")
